DROP TABLE COMMENT;
DROP TABLE ISSUELABEL;
DROP TABLE ISSUE;
DROP TABLE NEXTSTATE;
DROP TABLE PROJECTSTATE;
DROP TABLE STATE;
DROP TABLE PROJECTLABEL;
DROP TABLE LABEL;
DROP TABLE PROJECT;
DROP TABLE COLLABORATOR;

