INSERT INTO COLLABORATOR VALUES ('rui', 'patricio');
INSERT INTO COLLABORATOR VALUES ('fabio', 'cannavaro');
INSERT INTO STATE VALUES ('open');
INSERT INTO STATE VALUES ('closed');
INSERT INTO STATE VALUES ('archived');
INSERT INTO PROJECT VALUES ('daw', 'Daw phase1', 'open');
INSERT INTO PROJECTSTATE VALUES ('daw', 'open');
INSERT INTO PROJECTSTATE VALUES ('daw', 'closed');
INSERT INTO PROJECTSTATE VALUES ('daw', 'archived');
INSERT INTO LABEL VALUES ('test');
INSERT INTO LABEL VALUES ('labeling');
INSERT INTO PROJECTLABEL VALUES ('daw', 'test');
INSERT INTO PROJECTLABEL VALUES ('daw', 'labeling');
INSERT INTO NEXTSTATE VALUES ('daw', 'open', 'closed');
INSERT INTO NEXTSTATE VALUES ('daw', 'closed', 'archived');
INSERT INTO ISSUE VALUES ('daw', 'issue1', 'desc issue1', default, null, 'open');
INSERT INTO ISSUE VALUES ('daw', 'issue2', 'desc issue1', default, null, 'open');
INSERT INTO ISSUELABEL VALUES ('daw', 1, 'test');
INSERT INTO ISSUELABEL VALUES ('daw', 2, 'labeling');
INSERT INTO COMMENT VALUES ('daw', 1, 'comment1 bla', default);
INSERT INTO COMMENT VALUES ('daw', 2, 'comment1 bla bla', default);
INSERT INTO COMMENT VALUES ('daw', 2, 'comment2 bla bla', default);